### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dkeithdj** [dkeithdj/joes-cafe#2]
# Set of tasks needed to be done:
 
- [x] setup monorepo
- [x] migrate database to packages/
- [x] migrate ui to packages/
- [x] segregate existing customer application
- [x] create admin application
- [x] create kitchen application

**Comment by dkeithdj** [comment]
feel free to add here @d0o-o0p @deksheesh

**Comment by dkeithdj** [comment]
Decided to separate the api from the frontends
- [ ] migrate nextj api to fastify
- [ ] integrate  tRPC on backend
- [ ] integrate tRPC on frontend

**Comment by dkeithdj** [comment]
#4 Issue is to keep track of the additional features needed for the application
